<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>305eb8b8-938a-4d2d-add1-50607ecec2ec</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunDemo.ApiService\FunDemo.ApiService.csproj" />
    <ProjectReference Include="..\IdentityServer\IdentityServer.csproj" />
  </ItemGroup>

</Project>
